In [1]:
from vnstock_forecast.data import updater, query
import pandas as pd
from vnstock_forecast.shared.path import DATA_PATH_STR

In [2]:
test_df = pd.read_parquet(DATA_PATH_STR + "/ohlcv/resolution=D/SHB.parquet")
test_df

,Timestamp,Symbol,Open,High,Low,Close,Volume
0,1746748800,SHB,10827.98190,11083.76100,10785.35205,10998.50130,70367000.0
1,1747008000,SHB,10998.50130,11211.65055,10870.61175,11211.65055,84700800.0
2,1747094400,SHB,11254.28040,11382.16995,11083.76100,11169.02070,75244700.0
3,1747180800,SHB,11083.76100,11169.02070,10998.50130,11083.76100,52912000.0
4,1747267200,SHB,11041.13115,11851.09830,10955.87145,11680.57890,167912500.0
...,...,...,...,...,...,...,...
201,1772150400,SHB,16150.00000,16150.00000,15850.00000,15950.00000,38821900.0
202,1772409600,SHB,15300.00000,15850.00000,15200.00000,15650.00000,88122000.0
203,1772496000,SHB,15650.00000,15700.00000,15350.00000,15500.00000,53183400.0
204,1772582400,SHB,15450.00000,15550.00000,15000.00000,15500.00000,87559100.0
205,1772668800,SHB,15650.00000,15700.00000,15150.00000,15250.00000,67258100.0

In [3]:
df = query.query_ohlcv_grouped(
    symbols=["VHM", "SHB"],
    resolutions=["D", "W"],
    from_ts=1747008000,
    to_ts=1747267200,
)

In [4]:
df["D"]["SHB"]

                   Open         High          Low        Close       Volume
Timestamp
1747008000  10998.50130  11211.65055  10870.61175  11211.65055   84700800.0
1747094400  11254.28040  11382.16995  11083.76100  11169.02070   75244700.0
1747180800  11083.76100  11169.02070  10998.50130  11083.76100   52912000.0
1747267200  11041.13115  11851.09830  10955.87145  11680.57890  167912500.0

In [6]:

# query_ohlcv_grouped: kết quả dạng dict[resolution][symbol] → DataFrame (index = Date)
data = query.query_ohlcv_grouped(
    symbols=["SHB", "VHM"],
    resolutions=["D", "W"],
    from_ts=1747008000,
    to_ts=1747267200,
)

# Duyệt và hiển thị từng (resolution, symbol)
for resolution, symbols_dict in data.items():
    for symbol, df in symbols_dict.items():
        print(f"\n{'='*50}")
        print(f"  Resolution: {resolution}  |  Symbol: {symbol}  |  {len(df)} rows")
        print(f"{'='*50}")
        display(df)

==================================================
  Resolution: D  |  Symbol: SHB  |  4 rows
==================================================

                   Open         High          Low        Close       Volume
Timestamp
1747008000  10998.50130  11211.65055  10870.61175  11211.65055   84700800.0
1747094400  11254.28040  11382.16995  11083.76100  11169.02070   75244700.0
1747180800  11083.76100  11169.02070  10998.50130  11083.76100   52912000.0
1747267200  11041.13115  11851.09830  10955.87145  11680.57890  167912500.0

==================================================
  Resolution: D  |  Symbol: VHM  |  4 rows
==================================================

               Open     High      Low    Close      Volume
Timestamp
1747008000  62200.0  62800.0  61800.0  62300.0   5743300.0
1747094400  61800.0  62500.0  60900.0  62000.0   6806700.0
1747180800  61700.0  62000.0  60400.0  60400.0   6555600.0
1747267200  60200.0  60300.0  57100.0  58000.0  17963700.0

==================================================
  Resolution: W  |  Symbol: SHB  |  4 rows
==================================================

                   Open         High          Low        Close       Volume
Timestamp
1747008000  10998.50130  11211.65055  10870.61175  11211.65055   84700800.0
1747094400  11254.28040  11382.16995  11083.76100  11169.02070   75244700.0
1747180800  11083.76100  11169.02070  10998.50130  11083.76100   52912000.0
1747267200  11041.13115  11851.09830  10955.87145  11680.57890  167912500.0

==================================================
  Resolution: W  |  Symbol: VHM  |  4 rows
==================================================

               Open     High      Low    Close      Volume
Timestamp
1747008000  62200.0  62800.0  61800.0  62300.0   5743300.0
1747094400  61800.0  62500.0  60900.0  62000.0   6806700.0
1747180800  61700.0  62000.0  60400.0  60400.0   6555600.0
1747267200  60200.0  60300.0  57100.0  58000.0  17963700.0

In [ ]:

# Truy cập trực tiếp từng slice
data["D"]["SHB"]